apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: v32-backend
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - v32.germainleignel.com
      secretName: v32-backend-tls
  rules:
    - host: v32.germainleignel.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: v32-backend
                port:
                  number: 80
