apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: v32-backend
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: v32.gmn.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: v32-backend
                port:
                  number: 80
