apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret-pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: v32-backend
  app.kubernetes.io/component: api
